import numpy as np
import pickle
import tree
import pennylane as qml
import cmath
import sympy as sp
import utils

def generate_state(c, args, ideal_module, device, pathName, index):
	"""
	Generate the state we wnat to achieve

	Args:
		c (str): the state we want to achieve between a random state, |0>, or a state generated by a predefined circuit
		args (): the selected arguments
		ideal_module (): the module where the function to generate the state is
		device (): where to execute the circuit
		pathName (str): path to save the generated state
	
	Results:
		state (np.array): the generated state
	"""

	if c == 'random': 
		#generate state to be approximated
		real_part=np.random.normal(size=2**args.n_qubits)
		imag_part=np.random.normal(size=2**args.n_qubits)
		random_complex_vector=real_part+1j*imag_part
		norm=np.linalg.norm(random_complex_vector)

		state=random_complex_vector/norm
	elif c== 'zero':
		state = np.zeros(shape=(2**args.n_qubits), dtype=complex)
		state[0] += 1.0
	else:
		#obtain the state from a predefined circuit defined in ideal_circuiN* modules
		U=np.zeros(shape=(2**args.n_qubits,2**args.n_qubits),dtype=complex)
		circuit=getattr(ideal_module,c)
		state = circuit(device, args.n_qubits)([], U, args.device, True)

	if not args.only_test:
		fileParams = open(args.path + str(args.n_qubits) + 'qubit/' + str(index) + '/'+ 'ideal_' + pathName + '.obj', 'wb')
						
		pickle.dump(state, fileParams)
		fileParams.close()
	
	return state

def generate_tree_and_theta(state, args):
	"""
	Generate the tree with amplitudes and computes the multiplexor theta

	Args:
		state (np.array): the generated state
		args ():the given argument

	Returns:
		(): the list of theta
	"""
	######## Unitary Matrix Computation ########
	
	#generate the tree where in each root we will insert the corresponding amplitude
	tree_root = tree.build_sum_tree(state)
	#print_tree(tree_root)
	#input()
	
	#compute theta of multiplexors in order to calculate the U needed to prepare the desired state
	num_theta_multiplexor = 1
	for n in range(1, args.n_qubits):
		num_theta_multiplexor += 2**n
	theta_multiplexor = np.empty(shape=num_theta_multiplexor)

	#retrieve the list of amplitudes
	amplitude_dic = tree.explore_tree(tree_root)
	#print(amplitude_dic)
	#input()

	#compute the first theta
	theta_multiplexor[0] = np.arccos(amplitude_dic.get("0") / amplitude_dic.get(""))

	#computation of other thetas for multiplexors
	count_bit = 0
	i=1
	while(i < num_theta_multiplexor):
		count_bit += 1
		for j in range(i, i + 2**(count_bit)):
			#each theta is computed as the arccos of the node amplitude divided by its father amplitude
			amp1_key = f"{bin(j-i)[2:].zfill(count_bit)}0"
			amp2_key = f"{bin(j-i)[2:].zfill(count_bit)}"
			if amplitude_dic.get(amp2_key) != 0:
				theta_multiplexor[j] = np.arccos(amplitude_dic.get(amp1_key) / amplitude_dic.get(amp2_key))
			else:
				theta_multiplexor[j] = 0

		i += 2**(count_bit)

	return theta_multiplexor, num_theta_multiplexor

def compute_U(num_theta_multiplexor, theta_multiplexor, args):
	"""
	Compute the unitary matrix to obtain the state
	
	Args:
		num_theta_multiplexor (int): number of theta
		theta_multiplexor (np.array): list of thetas
		args (): the given arguments
		
	Returns:
		(): the unitary matrix
	"""
	U = []
	
	#the U matrix is computed as a multiplexor of Ry rotations.
	#we will start from the last qubit and multiply between them all the matrices with the different controls value,
	# until we will reach the first which has only an Ry rotation without control qubit
	theta_iterator = num_theta_multiplexor-1
	for n in range(args.n_qubits, 1, -1):
		temp = qml.matrix(qml.ControlledQubitUnitary(qml.RY.compute_matrix(theta_multiplexor[theta_iterator]*2), wires = n, control_wires = range(0, n-1), control_values = [1 for _ in range(0, n-1)]))
		#print(temp)
		#input()
		if n != args.n_qubits:
			temp = np.kron(temp, qml.Identity.compute_matrix(n_wires = args.n_qubits - n))
		
		theta_iterator -= 1

		for control in range(2**(n-1)-2, -1, -1):
			
			c_values = f"{bin(control)[2:].zfill(n-1)}"
			#print(c_values)
			#input()
			
			#print(c_values)
			temp2 = qml.matrix(qml.ControlledQubitUnitary(qml.RY.compute_matrix(theta_multiplexor[theta_iterator]*2), wires = n, control_wires = range(0, n-1), control_values = [int(c) for c in c_values]))
			if n != args.n_qubits:
				temp2 = np.kron(temp2, qml.Identity.compute_matrix(n_wires = args.n_qubits - n))
			temp = temp @ temp2

			theta_iterator -= 1
		
		if len(U) == 0:
			U = temp
		else:
			U = U @ temp
		
	#multiply by the Ry rotaion on the first qubit
	U = U @ np.kron(qml.RY.compute_matrix(theta_multiplexor[0]*2), qml.Identity.compute_matrix(n_wires = args.n_qubits-1))
	
	return U

def compute_Uphase(state, args):
	"""
	Compute the unitary matrix to obtain the state
	
	Args:
		state (np.array): the generated state
		args (): the given arguments
		
	Returns:
		(): the unitary matrix
	"""
	polar_state = []
	for s in state:
		polar_state.append(cmath.polar(s))

	#generate unitary matrix
	U_phase=np.zeros(shape=(2**args.n_qubits,2**args.n_qubits),dtype=complex)

	for i in range(2**args.n_qubits):
		U_phase[i, i] =   np.exp(1j * polar_state[i][1])

	return U_phase

def compute_SU(circuit, device, args, U_phase, X_train):
	"""
	Compute the special unitary matrix to obtain the state
	
	Args:
		circuit(): the circuit
		device (): where to execute the circuits
		args (): the given argument
		U_phase (): the unitary matrix for phase
		X_train (): the training set
		
	Returns:
		(): the list of special unitary matrix
		(): the label for phase
		(): the roots of determinant
	"""
	#if we want the precise state, we can have 2^n_qubits different SU based on the phases and we have to choose the correct one
	y_ideal_phase = [circuit(device, args.n_qubits)(x, U_phase, args.device, True) for x in X_train]

	#calculate the determinant of the unitary that we want to approximate
	det=np.linalg.det(U_phase)

	#calculate the 2^n roots of the determinant that give the 2^n possible SU's
	z=sp.symbols('z', complex=True)
	equation=z**(2**args.n_qubits)-det 
	solutions=sp.solve(equation,z)
	#print(solutions)
	solutions=[complex(sol.evalf()) for sol in solutions]
	#print("roots of the determinant:", solutions)
			
	#sorting the four roots: ++ -> -+ -> -- -> +- (counterclockwise arrangement starting from 0 radiant in the unitary cfr)
	polar=[cmath.polar(s) for s in solutions]
	#print(polar)
	polar=[p if p[1] >= 0 else (p[0], np.pi + (np.pi + p[1])) for p in polar]
	polar=utils.bubble_sort(polar)
	#print(polar)
	solutions = [cmath.rect(r,theta) for (r,theta) in polar]
	#print(solutions)

	#calculate the SU's associated to the 2^n roots
	listSU=[]

	for i in range(len(solutions)):
		SU=U_phase/solutions[i]	
		#format_matrix(SU)
		listSU.append(SU)

	return listSU, y_ideal_phase, solutions

	



